version: '3'

services:
  poker_srv:
    container_name: poker_srv
    build: server/
    restart: always
    ports: 
      - '9911:9911'
    links:
      - poker_postgres
      - poker_redis
  poker_postgres:
    container_name: poker_pg
    build: db/
    restart: always
    ports: 
      - '5432:5432'
    volumes:
      - ./data:/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: poker
  poker_redis:
    container_name: poker_redis
    image: redis:5.0.4
    restart: always
    ports:
      - '6379:6379'
  poker_web:
    container_name: poker_web
    build: client/
    restart: always
    ports: 
      - '9910:80'